services:
  go-rest-clean-plane-chi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SERVER_ADDRESS=:8081
      - ALLOWED_ORIGINS=*,http://localhost:3000
      - JWT_SECRET_KEY=hoge
      - DD_AGENT_HOST=datadog-agent
      - DD_AGENT_PORT=4317
      - DD_DOGSTATSD_HOST=datadog-agent    # DogStatsD接続先
      - DD_DOGSTATSD_PORT=8125             # DogStatsD接続ポート
    volumes:
      - go-modules:/go/pkg/mod
    depends_on:
      - datadog-agent

  datadog-agent:
    image: datadog/agent:latest
    ports:
      - "8126:8126"  # APM用ポート
      - "8125:8125/udp"
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_SITE=ap1.datadoghq.com
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_CONTAINER_EXCLUDE="name:datadog-agent"
      # メトリクス関連の設定を追加
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true  # 他のコンテナからのメトリクス受信を許可
      - DD_DOGSTATSD_ORIGIN_DETECTION=true   # コンテナタグの自動検出
      - DD_HOSTNAME=local-docker-host           # ホスト名の設定
      - DD_DOGSTATSD_TAG_CARDINALITY=high    # タグの詳細度設定
      # デバッグ設定
      - DD_LOG_LEVEL=debug
      - DD_APM_DEBUG=true
      - DD_DOGSTATSD_DEBUG=true             # DogStatsDのデバッグログを有効化
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw  # APMデータの永続化
      - /tmp/datadog-agent-run:/opt/datadog-agent/run:rw
    healthcheck:
      test: [ "CMD", "agent", "health" ]
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  go-modules:
