// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/NishimuraTakuya-nt/go-rest-clean-plane-chi/internal/adapters/primary/http/handlers"
	"github.com/NishimuraTakuya-nt/go-rest-clean-plane-chi/internal/adapters/primary/http/routes"
	"github.com/NishimuraTakuya-nt/go-rest-clean-plane-chi/internal/adapters/primary/http/routes/v1"
	"github.com/NishimuraTakuya-nt/go-rest-clean-plane-chi/internal/adapters/secondary/piyographql"
	"github.com/NishimuraTakuya-nt/go-rest-clean-plane-chi/internal/core/usecases"
	"github.com/NishimuraTakuya-nt/go-rest-clean-plane-chi/internal/infrastructure/auth"
	"github.com/NishimuraTakuya-nt/go-rest-clean-plane-chi/internal/infrastructure/logger"
	"net/http"
)

import (
	_ "github.com/NishimuraTakuya-nt/go-rest-clean-plane-chi/docs/swagger"
)

// Injectors from wire.go:

func InitializeAPI() (http.Handler, error) {
	loggerLogger := logger.NewLogger()
	healthcheckHandler := handlers.NewHealthcheckHandler(loggerLogger)
	healthcheckRouter := v1.NewHealthcheckRouter(healthcheckHandler)
	tokenService := auth.NewTokenService()
	authUsecase := usecases.NewAuthUsecase(tokenService)
	client := piyographql.NewClient(loggerLogger)
	sampleUsecase := usecases.NewSampleUsecase(loggerLogger, client)
	sampleHandler := handlers.NewSampleHandler(loggerLogger, sampleUsecase)
	sampleRouter := v1.NewSampleRouter(sampleHandler)
	authHandler := handlers.NewAuthHandler(loggerLogger, authUsecase)
	authRouter := v1.NewAuthRouter(authHandler)
	handler := routes.NewRouter(healthcheckRouter, authUsecase, sampleRouter, authRouter)
	return handler, nil
}
